# Generated by Django 6.0.2 on 2026-03-23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0003_alter_chatmessage_created_at_alter_chatmessage_role_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="retrieved_context",
            field=models.TextField(blank=True, default="", verbose_name="检索上下文"),
        ),
    ]

