# Generated by Django 6.0.2 on 2026-03-20 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membershipproduct',
            options={'verbose_name': '会员卡产品', 'verbose_name_plural': '会员卡产品'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': '支付订单', 'verbose_name_plural': '支付订单'},
        ),
        migrations.AlterField(
            model_name='membershipproduct',
            name='days_duration',
            field=models.IntegerField(help_text='会员有效期天数', verbose_name='有效期(天)'),
        ),
        migrations.AlterField(
            model_name='membershipproduct',
            name='name',
            field=models.CharField(max_length=100, verbose_name='产品名称'),
        ),
        migrations.AlterField(
            model_name='membershipproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='价格'),
        ),
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='支付金额'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.membershipproduct', verbose_name='购买产品'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', '待支付'), ('paid', '已支付'), ('refunding', '退款中'), ('refunded', '已退款'), ('failed', '支付失败/已关闭')], default='pending', max_length=50, verbose_name='订单状态'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='退款原因')),
                ('status', models.CharField(choices=[('pending', '退款处理中'), ('success', '退款成功'), ('failed', '退款失败')], default='pending', max_length=50, verbose_name='退款状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='refund', to='orders.order', verbose_name='关联订单')),
            ],
            options={
                'verbose_name': '退款申请',
                'verbose_name_plural': '退款申请',
                'ordering': ['-created_at'],
            },
        ),
    ]
