# Generated by Django 6.0.2 on 2026-03-23 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_membershipproduct_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipproduct',
            name='is_promotion',
            field=models.BooleanField(default=False, verbose_name='是否促销'),
        ),
        migrations.AddField(
            model_name='membershipproduct',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='原价'),
        ),
        migrations.AddField(
            model_name='membershipproduct',
            name='tags',
            field=models.JSONField(blank=True, default=list, verbose_name='标签'),
        ),
    ]
