# Generated by Django 6.0.2 on 2026-04-02 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_membershipproduct_is_promotion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='out_trade_no',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='商户订单号'),
        ),
    ]
