# Generated by Django 6.0.2 on 2026-02-24 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BodyPart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, unique=True, verbose_name="锻炼部位"),
                ),
            ],
            options={
                "verbose_name": "锻炼部位",
                "verbose_name_plural": "锻炼部位",
            },
        ),
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="器械名称")),
                ("description", models.TextField(blank=True, verbose_name="器械描述")),
                (
                    "location",
                    models.CharField(
                        help_text="如: 有氧区, 力量区", max_length=50, verbose_name="位置区域"
                    ),
                ),
                (
                    "gif_url",
                    models.URLField(blank=True, null=True, verbose_name="演示动图URL"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="equipment/",
                        verbose_name="器械图片",
                    ),
                ),
                (
                    "part",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipments",
                        to="fitness.bodypart",
                        verbose_name="锻炼部位",
                    ),
                ),
            ],
            options={
                "verbose_name": "健身器械",
                "verbose_name_plural": "健身器械",
            },
        ),
    ]
