# Generated by Django 6.0.2 on 2026-02-27 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fitness", "0002_course_booking"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="姓名")),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("coach", "私人教练"),
                            ("therapist", "理疗师"),
                            ("frontdesk", "前台"),
                        ],
                        max_length=20,
                        verbose_name="角色",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="手机号"
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True, null=True, upload_to="team/", verbose_name="头像"
                    ),
                ),
                ("bio", models.TextField(blank=True, verbose_name="简介")),
                ("is_active", models.BooleanField(default=True, verbose_name="在职")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "团队成员",
                "verbose_name_plural": "团队成员",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="booking",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "课程预约",
                "verbose_name_plural": "课程预约",
            },
        ),
        migrations.AlterModelOptions(
            name="course",
            options={
                "ordering": ["-start_time"],
                "verbose_name": "课程安排",
                "verbose_name_plural": "课程安排",
            },
        ),
        migrations.AlterField(
            model_name="booking",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="fitness.course",
                verbose_name="课程",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="预约时间"),
        ),
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[("booked", "已预约"), ("cancelled", "已取消"), ("completed", "已完成")],
                default="booked",
                max_length=20,
                verbose_name="状态",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="booked_count",
            field=models.IntegerField(default=0, verbose_name="已预约人数"),
        ),
        migrations.AlterField(
            model_name="course",
            name="capacity",
            field=models.IntegerField(default=20, verbose_name="最大容量"),
        ),
        migrations.AlterField(
            model_name="course",
            name="coach_name",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="教练姓名"
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="duration",
            field=models.IntegerField(default=60, verbose_name="时长(分钟)"),
        ),
        migrations.AlterField(
            model_name="course",
            name="name",
            field=models.CharField(max_length=100, verbose_name="课程名称"),
        ),
        migrations.AlterField(
            model_name="course",
            name="start_time",
            field=models.DateTimeField(verbose_name="开始时间"),
        ),
        migrations.AddField(
            model_name="course",
            name="coach",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="courses",
                to="fitness.teammember",
                verbose_name="教练",
            ),
        ),
    ]
