# Generated by Django 6.0.2 on 2026-02-27 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fitness", "0003_teammember_alter_booking_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CheckIn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[("face", "人脸"), ("qr", "扫码"), ("manual", "人工")],
                        default="manual",
                        max_length=20,
                        verbose_name="方式",
                    ),
                ),
                (
                    "checkin_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="入场时间"),
                ),
                (
                    "checkout_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="离场时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "入场记录",
                "verbose_name_plural": "入场记录",
                "ordering": ["-checkin_time"],
            },
        ),
        migrations.CreateModel(
            name="EquipmentUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(verbose_name="开始时间")),
                (
                    "ended_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="结束时间"),
                ),
                (
                    "duration_minutes",
                    models.IntegerField(default=0, verbose_name="使用时长(分钟)"),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fitness.equipment",
                        verbose_name="器械",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "器械使用记录",
                "verbose_name_plural": "器械使用记录",
                "ordering": ["-started_at"],
            },
        ),
    ]
