# Generated by Django 6.0.2 on 2026-03-20 06:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fitness", "0004_checkin_equipmentusage"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkin",
            name="device_id",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="设备ID"
            ),
        ),
    ]
