# Generated by Django 6.0.2 on 2026-04-10 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0006_equipmentrepair'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='precautions',
            field=models.TextField(blank=True, verbose_name='注意事项'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='status',
            field=models.CharField(choices=[('idle', '空闲'), ('in_use', '使用中'), ('maintenance', '维修中')], default='idle', max_length=20, verbose_name='器械状态'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='target_muscles',
            field=models.CharField(blank=True, max_length=200, verbose_name='目标肌群'),
        ),
    ]
