# Generated by Django 6.0.2 on 2026-04-13 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0007_equipment_precautions_equipment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='action_tips',
            field=models.TextField(blank=True, verbose_name='动作要点'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='miniapp_gif_path',
            field=models.CharField(blank=True, max_length=255, verbose_name='小程序动图路径'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='training_focus',
            field=models.CharField(blank=True, max_length=200, verbose_name='训练定位'),
        ),
    ]
