"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

def _env(key: str, default: str | None = None) -> str | None:
    return os.getenv(key, default)


def _env_bool(key: str, default: bool = False) -> bool:
    v = os.getenv(key)
    if v is None:
        return default
    return v.strip().lower() in {"1", "true", "yes", "y", "on"}


def _env_float(key: str, default: float) -> float:
    v = os.getenv(key)
    if v is None:
        return default
    try:
        return float(v.strip())
    except Exception:
        return default


DEBUG = _env_bool("DJANGO_DEBUG", True)
SECRET_KEY = _env("DJANGO_SECRET_KEY", "dev-unsafe-secret-key")
if not DEBUG and SECRET_KEY == "dev-unsafe-secret-key":
    raise ImproperlyConfigured("DJANGO_SECRET_KEY is required when DJANGO_DEBUG is false")

ALLOWED_HOSTS = [h.strip() for h in (_env("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")) if h.strip()]


# Application definition

INSTALLED_APPS = [
    "simpleui",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Third party apps
    "rest_framework",
    "rest_framework_simplejwt",
    "corsheaders",
    "drf_spectacular", # API 文档
    # Local apps
    "common.apps.CommonConfig", # 公共组件
    "users.apps.UsersConfig",
    "fitness.apps.FitnessConfig",
    "bot.apps.BotConfig",
    "orders.apps.OrdersConfig",
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'EXCEPTION_HANDLER': 'common.exceptions.custom_exception_handler',
}

# Swagger 文档配置
SPECTACULAR_SETTINGS = {
    'TITLE': 'Trae Fitness API',
    'DESCRIPTION': '企业级智能健身房管理系统 API 接口文档',
    'VERSION': '2.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    # 'OTHER_SETTINGS': ...
}

BAIDU_AI_CONFIG = {
    "APP_ID": _env("BAIDU_APP_ID", ""),
    "API_KEY": _env("BAIDU_API_KEY", ""),
    "SECRET_KEY": _env("BAIDU_SECRET_KEY", ""),
    "FACE_GROUP": _env("BAIDU_FACE_GROUP", "irongym_members"),
}
FACE_VERIFY_SCORE_THRESHOLD = _env_float("FACE_VERIFY_SCORE_THRESHOLD", 80.0)

BAIDU_AI_FALLBACK = {
    "FACE_VERIFY": _env("BAIDU_FACE_VERIFY_FALLBACK", "otp_code"),
    "AI_RESPONSE": _env("BAIDU_AI_RESPONSE_FALLBACK", "cached_responses"),
}

RAG_SERVICE_URL = _env("RAG_SERVICE_URL", "http://127.0.0.1:9000/rag/search")
RAG_SERVICE_MODE = (_env("RAG_SERVICE_MODE", "context") or "context").strip().lower()
RAG_SERVICE_TIMEOUT = _env_float("RAG_SERVICE_TIMEOUT", 60.0)
LLM_API_KEY = _env("LLM_API_KEY", _env("MOLIFANGZHOU_API_KEY", "") or _env("GITEE_AI_API_KEY", ""))
LLM_BASE_URL = _env("LLM_BASE_URL", _env("MOLIFANGZHOU_BASE_URL", "https://ai.gitee.com/v1"))
LLM_MODEL = _env("LLM_MODEL", _env("MOLIFANGZHOU_MODEL", "MiniMax-M2.5"))

KNOWLEDGE_BASE = {
    "vector_db": _env("VECTOR_DB", "faiss"),
    "documents": [p.strip() for p in (_env("KNOWLEDGE_DOCUMENTS", "data/会员入场手册.pdf,data/Wi-Fi连接指南.md,data/器材报修流程.docx").split(",")) if p.strip()],
}

DASHBOARD_SHOW_EQUIPMENT_HEATMAP = _env_bool("DASHBOARD_SHOW_EQUIPMENT_HEATMAP", False)

# 日志配置 (企业级)
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'level': 'ERROR',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'django_error.log',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}

from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=7),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=14),
}

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware", # Added CorsMiddleware
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

AUTH_USER_MODEL = 'users.UserProfile'

CORS_ALLOW_ALL_ORIGINS = DEBUG
if not CORS_ALLOW_ALL_ORIGINS:
    CORS_ALLOWED_ORIGINS = [o.strip() for o in (_env("CORS_ALLOWED_ORIGINS", "").split(",")) if o.strip()]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'templates'],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

USE_POSTGRES = _env_bool("USE_POSTGRES", False)

if USE_POSTGRES:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": _env("POSTGRES_DB", "fitness_db"),
            "USER": _env("POSTGRES_USER", "postgres"),
            "PASSWORD": _env("POSTGRES_PASSWORD", "postgres"),
            "HOST": _env("POSTGRES_HOST", "127.0.0.1"),
            "PORT": _env("POSTGRES_PORT", "5432"),
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

_password_min_length = int(_env("DJANGO_PASSWORD_MIN_LENGTH", "6" if DEBUG else "10") or "10")
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator", "OPTIONS": {"min_length": _password_min_length}},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "zh-hans"

TIME_ZONE = "Asia/Shanghai"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
}

# 登录安全配置
LOGIN_URL = '/admin/login/'
LOGIN_REDIRECT_URL = '/admin/'

# 会话设置
SESSION_COOKIE_AGE = 3600  # 1小时
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# SimpleUI 配置
SIMPLEUI_HOME_INFO = False  # 隐藏首页的 SimpleUI 信息
SIMPLEUI_ANALYSIS = False   # 关闭使用分析
SIMPLEUI_LOGO = '/static/admin/simpleui-x/img/logo-theme.svg'
SIMPLEUI_DEFAULT_THEME = 'trae.css' # 设置默认主题为自定义主题
SIMPLEUI_INDEX = 'https://www.baidu.com' # 可以设置默认打开的页面

# 隐藏顶部右侧的部分工具按钮，让界面更清爽
SIMPLEUI_HOME_QUICK = False # 隐藏首页快捷操作
SIMPLEUI_HOME_ACTION = False # 隐藏首页最近动作

# 自定义 SimpleUI 菜单
SIMPLEUI_CONFIG = {
    'system_keep': False,
    'menu_display': ['场馆运营', '交易管理', 'AI服务', '用户中心', '系统设置'],
    'dynamic': True,
    'menus': [
        {
            'name': '场馆运营',
            'icon': 'fas fa-dumbbell',
            'models': [
                {
                    'name': '器械管理',
                    'icon': 'fas fa-cogs',
                    'url': 'fitness/equipment/'
                },
                {
                    'name': '部位管理',
                    'icon': 'fas fa-child',
                    'url': 'fitness/bodypart/'
                },
                {
                    'name': '课程排期',
                    'icon': 'fas fa-calendar-alt',
                    'url': 'fitness/course/'
                },
                {
                    'name': '教练团队',
                    'icon': 'fas fa-users',
                    'url': 'fitness/teammember/'
                },
                {
                    'name': '设备报修',
                    'icon': 'fas fa-tools',
                    'url': 'fitness/equipmentrepair/'
                },
                {
                    'name': '打卡记录',
                    'icon': 'fas fa-check-circle',
                    'url': 'fitness/checkin/'
                }
            ]
        },
        {
            'name': '交易管理',
            'icon': 'fas fa-shopping-cart',
            'models': [
                {
                    'name': '订单列表',
                    'icon': 'fas fa-clipboard-list',
                    'url': 'orders/order/'
                },
                {
                    'name': '会员卡产品',
                    'icon': 'fas fa-id-card',
                    'url': 'orders/membershipproduct/'
                },
                {
                    'name': '退款申请',
                    'icon': 'fas fa-hand-holding-usd',
                    'url': 'orders/refund/'
                }
            ]
        },
        {
            'name': 'AI服务',
            'icon': 'fas fa-robot',
            'models': [
                {
                    'name': '对话会话',
                    'icon': 'fas fa-comments',
                    'url': 'bot/chatsession/'
                },
                {
                    'name': '消息记录',
                    'icon': 'fas fa-comment-dots',
                    'url': 'bot/chatmessage/'
                }
            ]
        },
        {
            'name': '用户中心',
            'icon': 'fas fa-user-circle',
            'models': [
                {
                    'name': '会员档案',
                    'icon': 'fas fa-user-edit',
                    'url': 'users/userprofile/'
                },
                {
                    'name': '意见反馈',
                    'icon': 'fas fa-envelope-open-text',
                    'url': 'users/feedback/'
                }
            ]
        },
        {
            'name': '系统设置',
            'icon': 'fas fa-cog',
            'models': [
                {
                    'name': '接口文档',
                    'icon': 'fas fa-book',
                    'url': '/api/docs/'
                }
            ]
        }
    ]
}

# 首页看板配置
SIMPLEUI_HOME_PAGE = '/dashboard/' # 设置自定义首页
SIMPLEUI_HOME_TITLE = '实时运营看板' # 首页标题
SIMPLEUI_HOME_ICON = 'fa fa-tachometer-alt' # 首页图标

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# 云存储配置 (OSS/COS)
USE_OSS = _env_bool("USE_OSS", False)
if USE_OSS:
    OSS_ACCESS_KEY_ID = _env("OSS_ACCESS_KEY_ID", "")
    OSS_ACCESS_KEY_SECRET = _env("OSS_ACCESS_KEY_SECRET", "")
    OSS_BUCKET_NAME = _env("OSS_BUCKET_NAME", "")
    OSS_ENDPOINT = _env("OSS_ENDPOINT", "")
    OSS_CNAME = _env("OSS_CDN_DOMAIN", "")
    STORAGES["default"] = {
        "BACKEND": "common.oss_storage.AliyunOssStorage",
    }
    if OSS_CNAME:
        MEDIA_URL = f'https://{OSS_CNAME}/'
    else:
        MEDIA_URL = f'https://{OSS_BUCKET_NAME}.{OSS_ENDPOINT}/'
